### ISSUE TITLE
Error Message: "Optimal parameters not found"

### ISSUE THREAD

**Issue by lgelman** [fmi-faim/napari-psf-analysis#18] opened 2022-10-25 07:08 UTC
This error message appeared when analysing images taken with the 63x objective on the W1_Levi-M on 03/10/2022. 
![Screenshot 2022-10-21 003630](https://user-images.githubusercontent.com/10118256/197706217-6f6d65f8-0ca2-4900-8631-b6a48ec0362d.png).

**Comment by tibuch** [comment] 2022-10-25 07:13
Thank you for reporting.

Looks like no fit was found for the bead. Could you attach the file in question as `.zip`? Then I can try to reproduce the issue.

**Comment by lgelman** [comment] 2022-10-25 07:20
Heree is the link to the folder:
\\imagestore\faim\Maintenance_All_microscopes\Maintenance_W1_Levi\Maintenance_weekly\PSF\20221003

**Comment by clairemitchell308** [comment] 2022-10-25 16:31
Hello, thank you for the nice plugin! I can confirm I am also finding this issue. 

> RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 1600.

When I select a few points by hand, I don't receive this error but then it occurs when I try to add more and more points, suggesting it is a few beads that are the issue. 

Maybe a useful feature would be for the plugin to skip-over beads it cannot fit and continue with the next one? 

Happy to also upload my example images somewhere if that would be helpful. One is an AiryScan processed one so I am surprised to see it cannot fit as the SNR is quite good.

**Comment by lgelman** [comment] 2022-10-26 08:41
> 

Hi CLaire,
Thanks for the feed-back.
Until this is solved, you can use a smaller PSF box size, like 4000 instead of 6000. It worked for me well.
Cheers,
Laurent.

**Comment by clairemitchell308** [comment] 2022-10-27 10:07
Hi Laurent

Thank you for the suggestion, unfortunately even when I change the box size I still see this error. 

I also tested choosing only the beads which were furthest away from each other in case overlap of the bounding box with other beads was an issue but still receive the same error. Also, I have seen with other datasets that the fitting is quite robust to the prescence of other beads on the periphery.

Thanks
Claire

**Comment by lgelman** [comment] 2022-10-27 11:01
Hi Claire,
Sorry that you experience these problems. At the same time, it is very helpful for us to have your feedback before we distribute the macro to other potentially interested people.
Would it be possible for you to upload a file where you get this error? We could use it on our side to test new implementations of the fit.
Thanks a lot for your collaboration,
Cheers,
L.

**Comment by clairemitchell308** [comment] 2022-10-28 08:56
Hi Laurent

No problem at all, happy to help! Sorry for finding problems with it!

I have sent over an example file which is causing a problem, hopefully you can access it. The beads are quite dense but I am selecting the less dense ones. (On that note, I wrote a napari script to automatically segment beads, place points at the bead locations and then filter out the ones a certain distance from each other, I attach for your interest as it might be helpful if you are lazy like me!).

Best wishes
Claire

**Comment by clairemitchell308** [comment] 2022-10-28 09:22
Hi 

Sorry to add another comment to this but I was rerunning some image of beads that previously worked and now they don't seem to. I guess either it's something to do with the updated plugin (I'm afraid I don't know how to rollback ones installed using the napari plugin installer) or I guess something in my machine. Will be interested to see what you get with the data I sent over.

Best wishes
Claire

**Comment by lgelman** [comment] 2022-10-28 10:51
Hi Claire,

I am really sorry to hear you have now even more issue.
I am so grateful for your contribution to “automatic bead finding”. We will discuss how we can implement this in the plugin. Actually, this is exactly why we decided to move to python and Napari, to open this project and the coding to the community. So, again, thanks for this!

We will discuss all that internally on Monday and will let you know our plans.

In the meantime, I wish you a very nice weekend,

Cheers,

Laurent.

**Comment by tibuch** [comment] 2022-11-10 15:21
Hello everyone,

This issue should be solved with the new version 0.2.3. You can install it by running `pip install napari-psf-analysis --upgrade`.

Happy analyzing!

**Comment by clairemitchell308** [comment] 2022-11-10 16:24
Hi @tibuch 

I'm afraid to say this fix changed the error a little bit but hasn't eliminated it completely. 

Now instead I see:

> RuntimeError: Optimal parameters not found: The maximum number of function evaluations is exceeded.

I drag and drop the zip file below, hopefully it works okay for you

[63x_AS_90degScannerRotation_Airyscan Processing.zip](https://github.com/fmi-faim/napari-psf-analysis/files/9982794/63x_AS_90degScannerRotation_Airyscan.Processing.zip)

Many thanks, Claire

**Comment by tibuch** [comment] 2022-11-10 16:33
Hi @clairemitchell308,

Thank you for the file.

I just picked one bead at random for which it worked. I assume that there are some beads which don't work. Would it be fine if these are just skipped?

**Comment by clairemitchell308** [comment] 2022-11-10 16:35
Hi @tibuch 

Yes this would be okay for me. As long as it works for your development of the plugin. I guess maybe a comment to say it was skipped would be helpful?

Many thanks

**Closed** 2022-11-17 13:29 UTC

**Comment by tibuch** [comment] 2022-11-17 13:39
@clairemitchell308 I am now catching the error when no fit is found and report it in the UI. I tested it with your example image and it works for me.

The new version (v0.2.4) should soon be available on pypi. Please let me know if you run into any other issues.

Thanks!
